common:
  profile: ${PROFILE}
  mocks: ${MOCKS}
  webclient-timeout: ${WEBCLIENT_TIME_OUT}

static:
  smp-public-key-crypto: ${SMP_PUBLIC_KEY}
  smp-private-key-crypto: ${SMP_PRIVATE_KEY}
  smp-private-key-iv-crypto: ${SMP_PRIVATE_KEY_IV}
  smp-private-key-password-crypto: ${SMP_PRIVATE_KEY_PASSWORD}
  error-messages: ${SMP_NTF_ERRORS}
  is-customer-products-session-integrity-enabled: ${IS_CUSTOMER_PRODUCTS_SESSION_INTEGRITY_ENABLED}
