# governance-standard: v1.0.0
name: "Rollback - PRD"
run-name: "Rollback PRD [${{ inputs.oc }}] ${{ inputs.version }}"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to rollback (version or revision)'
        required: true
        default: ''
      oc:
        description: 'Orden de cambio (OC)'
        required: true
        default: ''

jobs:
  ROLLBACK-PRD:
    uses: ExampleCorppe-platform-org/dso-k8s-reusable/.github/workflows/_cd-aks-rollback-prd.yml@v1 # NOSONAR - internal reusable workflow
    permissions:
      contents: write
      id-token: write
      attestations: write
      issues: write
    with:
      application: smp
      component-name: smp-notification
      version: ${{ github.event.inputs.version }}
      oc: ${{ github.event.inputs.oc }}
      component-type: backend
      build-type: java-mvn
    secrets: inherit # NOSONAR - dynamic app secrets
